//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class registers
    {
        public long Id { get; set; }
        public long EventId { get; set; }
        public string User { get; set; }
    
        public virtual events events { get; set; }
        public virtual users users { get; set; }
    }
}
