//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.events = new HashSet<events>();
            this.registers = new HashSet<registers>();
        }
    
        public string Login { get; set; }
        public string Haslo { get; set; }
        public long Rola { get; set; }
        public long Wiek { get; set; }
    
        public virtual ICollection<events> events { get; set; }
        public virtual ICollection<registers> registers { get; set; }
    }
}
