//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        public events()
        {
            this.register = new HashSet<register>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public System.DateTime Data { get; set; }
        public int IloscMiejsc { get; set; }
        public int IloscWolnych { get; set; }
        public string Miejsce { get; set; }
        public int Prowadzacy { get; set; }
    
        public virtual ICollection<register> register { get; set; }
        public virtual users users { get; set; }
    }
}
