//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.events = new HashSet<events>();
            this.register = new HashSet<register>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Haslo { get; set; }
        public int Rola { get; set; }
    
        public virtual ICollection<events> events { get; set; }
        public virtual ICollection<register> register { get; set; }
    }
}
